// src/constants/stockData.js

export const NAV_LINKS = ['Tableau de bord', 'Mouvement', 'Stock', 'Réception'];

export const STOCK_DATA = [
  {
    code:        'SAP-10492',
    designation: 'Roulement à billes SKF 6205-2RS',
    categorie:   'Mécanique',
    emplacement: 'Allée A - Rayon 4',
    qty:         145,
    seuil:       50,
    etat:        'Optimal',
  },
  {
    code:        'SAP-28571',
    designation: 'Filtre à huile Caterpillar 1R-0749',
    categorie:   'Consommable',
    emplacement: 'Allée C - Rayon 2',
    qty:         24,
    seuil:       20,
    etat:        'Faible',
  },
  {
    code:        'SAP-09211',
    designation: 'Courroie de transmission optibelt',
    categorie:   'Mécanique',
    emplacement: 'Allée B - Rayon 1',
    qty:         2,
    seuil:       10,
    etat:        'Critique',
  },
  {
    code:        'SAP-44820',
    designation: 'Capteur de pression Siemens SITRANS',
    categorie:   'Électrique',
    emplacement: 'Armoire Sécurisée 1',
    qty:         18,
    seuil:       5,
    etat:        'Optimal',
  },
  {
    code:        'SAP-55102',
    designation: 'Pompe centrifuge KSB Eta',
    categorie:   'Hydraulique',
    emplacement: 'Zone Pompage B3',
    qty:         3,
    seuil:       2,
    etat:        'Faible',
  },
  {
    code:        'SAP-33904',
    designation: 'Vanne à boisseau sphérique 2"',
    categorie:   'Tuyauterie',
    emplacement: 'Allée D - Rayon 5',
    qty:         42,
    seuil:       10,
    etat:        'Optimal',
  },
  {
    code:        'SAP-88271',
    designation: 'Contacteur Schneider LC1D09',
    categorie:   'Électrique',
    emplacement: 'Armoire A2',
    qty:         12,
    seuil:       15,
    etat:        'Faible',
  },
  {
    code:        'SAP-11200',
    designation: 'Joint à lèvre Viton 50x72x10',
    categorie:   'Mécanique',
    emplacement: 'Allée A - Rayon 8',
    qty:         0,
    seuil:       20,
    etat:        'Critique',
  },
  {
    code:        'SAP-66512',
    designation: 'Moteur asynchrone 5.5kW ABB',
    categorie:   'Électrique',
    emplacement: 'Zone Gros Stock',
    qty:         4,
    seuil:       2,
    etat:        'Optimal',
  },
  {
    code:        'SAP-44109',
    designation: 'Graisse industrielle Shell Gadus',
    categorie:   'Consommable',
    emplacement: 'Allée C - Rayon 10',
    qty:         85,
    seuil:       30,
    etat:        'Optimal',
  },
];